package main

import (
	"bufio"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

// Cached one-paragraph summaries of what a session was actually about.
//
// Generated by each provider's own CLI in non-interactive mode, so the work is
// billed to that agent's existing subscription and orbit needs no API keys of
// its own. Cheap models are the right tool here — this is summarising, not
// reasoning — and the command is configurable per provider precisely so you can
// pick one.
//
// The cache key includes the session's last event time, so a summary is
// computed once per conversation state and silently regenerates if the session
// is continued.

const summaryPrompt = `Summarise this coding session transcript in 2-3 short sentences.
Say what the user was trying to do and how it ended (finished, abandoned, blocked).
Be concrete: name the files, tools or errors involved. No preamble, no bullet
points, no offers to help — just the summary.

TRANSCRIPT EXCERPT:
`

func summaryDir() string { return home(".cache", "orbit", "summaries") }

func summaryKey(s *Session) string {
	sum := sha256.Sum256([]byte(s.Agent.String() + s.ID + s.Modified.UTC().Format(time.RFC3339)))
	return hex.EncodeToString(sum[:8])
}

func summaryFile(s *Session) string {
	return filepath.Join(summaryDir(), s.Agent.String()+"-"+s.ID+"-"+summaryKey(s)+".txt")
}

// CachedSummary returns a previously generated summary, if one exists for this
// exact session state.
func CachedSummary(s *Session) (string, bool) {
	b, err := os.ReadFile(summaryFile(s))
	if err != nil {
		return "", false
	}
	return strings.TrimSpace(string(b)), true
}

// GenerateSummary runs the provider's command with an excerpt on stdin. It is
// slow — several seconds — so callers should treat it as a background job.
func GenerateSummary(s *Session, cfg Summary) (string, error) {
	argv := cfg.For(s.Agent)
	if len(argv) == 0 {
		return "", errNoCommand
	}
	excerpt, err := transcriptExcerpt(s, cfg.InputBudget(s.Agent))
	if err != nil {
		return "", err
	}

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()

	cmd := exec.CommandContext(ctx, argv[0], argv[1:]...)
	cmd.Stdin = strings.NewReader(summaryPrompt + excerpt)
	cmd.Dir = s.Cwd // some CLIs refuse to start outside a workspace
	out, err := cmd.Output()
	if err != nil {
		return "", err
	}

	text := strings.TrimSpace(string(out))
	if cfg.MaxChars > 0 {
		text = truncate(text, cfg.MaxChars)
	}
	if text == "" {
		return "", errEmptySummary
	}
	if err := os.MkdirAll(summaryDir(), 0o755); err == nil {
		os.WriteFile(summaryFile(s), []byte(text), 0o644)
	}
	return text, nil
}

type summaryError string

func (e summaryError) Error() string { return string(e) }

const (
	errNoCommand    = summaryError("no summary command configured for this provider")
	errEmptySummary = summaryError("summariser returned nothing")
)

// transcriptExcerpt builds the prompt input: the opening of the conversation
// plus its tail. The middle is where tool output lives, which is bulky and
// tells you least about intent.
func transcriptExcerpt(s *Session, maxChars int) (string, error) {
	const (
		headLines = 12
		tailLines = 40
	)
	if maxChars <= 0 {
		maxChars = 12000
	}
	if s.Path == "" {
		// Copilot: no transcript file, so use what the database gave us.
		return "Title: " + s.Title + "\nLast prompt: " + s.Last, nil
	}

	f, err := os.Open(s.Path)
	if err != nil {
		return "", err
	}
	defer f.Close()

	var head, tail []string
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 256*1024), 64*1024*1024)
	for sc.Scan() {
		text := strings.TrimSpace(clean(recordText(sc.Bytes())))
		if text == "" {
			continue
		}
		text = truncate(text, 600)
		if len(head) < headLines {
			head = append(head, text)
			continue
		}
		tail = append(tail, text)
		if len(tail) > tailLines {
			tail = tail[1:]
		}
	}

	parts := head
	if len(tail) > 0 {
		parts = append(parts, "[...]")
		parts = append(parts, tail...)
	}
	out := strings.Join(parts, "\n")
	if len(out) > maxChars {
		// Keep both ends: the opening says what the session was for, the tail
		// says how it went. Cutting only the front would lose the intent.
		half := maxChars / 2
		out = out[:half] + "\n[...]\n" + out[len(out)-half:]
	}
	if strings.TrimSpace(out) == "" {
		return "", errEmptySummary
	}
	return out, nil
}

// PruneSummaries drops cache entries for sessions that have moved on, so the
// directory doesn't grow without bound as conversations continue.
func PruneSummaries(sessions []*Session) {
	live := map[string]bool{}
	for _, s := range sessions {
		live[filepath.Base(summaryFile(s))] = true
	}
	entries, err := os.ReadDir(summaryDir())
	if err != nil {
		return
	}
	for _, e := range entries {
		if !live[e.Name()] {
			os.Remove(filepath.Join(summaryDir(), e.Name()))
		}
	}
}
