package summary

import (
	"bufio"
	"context"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/sadrig91/orbit/internal/format"

	"github.com/sadrig91/orbit/internal/config"

	"github.com/sadrig91/orbit/internal/session"
)

// Cached summaries of what a session was actually about.
//
// Generated by each provider's own CLI in non-interactive mode, so the work is
// billed to that agent's existing subscription and orbit needs no API keys of
// its own. Cheap models are the right tool — this is summarising, not reasoning
// — and the command is configurable per provider precisely so you can pick one.
//
// A summary records how much of the conversation it covers. When the session
// continues the summary becomes stale rather than invalid, and the next
// regeneration sends the existing summary plus only the messages since. The
// alternative — re-reading the whole transcript every turn — makes keeping a
// long, active session summarised the most expensive thing orbit could do.

// MaxIncrements caps how many times a summary may be updated from its own
// previous text before being rebuilt from the transcript. Rolling summaries
// compound their own omissions; periodically starting over bounds the drift.
const MaxIncrements = 5

const fullPrompt = `Summarise this coding session transcript in 2-3 short sentences.
Say what the user was trying to do and how it ended (finished, abandoned, blocked).
Be concrete: name the files, tools or errors involved. No preamble, no bullet
points, no offers to help — just the summary.

TRANSCRIPT EXCERPT:
`

const updatePrompt = `Below is an existing summary of a coding session, then the messages that have
happened since it was written. Produce an updated summary of the session as a
whole, in 2-3 short sentences, in the same style. Keep what still matters from
the existing summary and fold in what changed. Do not describe the update
itself. No preamble, no bullet points — just the summary.

EXISTING SUMMARY:
{{PREV}}

NEW MESSAGES SINCE:
`

// Record is what gets cached: the text, plus a watermark of how much of
// the conversation it accounts for.
type Record struct {
	Text         string    `json:"summary"`
	CoveredUntil time.Time `json:"covered_until"`
	CoveredMsgs  int       `json:"covered_msgs"`
	Generation   int       `json:"generation"` // incremental updates since a full rebuild
	Written      time.Time `json:"written"`
}

// Stale reports whether the session has moved on since the summary was written.
// Message count is the signal rather than timestamps, because it is unaffected
// by the housekeeping records agents append to old transcripts.
func (r Record) Stale(s *session.Session) bool { return s.Msgs > r.CoveredMsgs }

// Behind is how many messages the summary hasn't seen.
func (r Record) Behind(s *session.Session) int { return max(0, s.Msgs-r.CoveredMsgs) }

func Dir() string { return format.Home(".cache", "orbit", "summaries") }

// Keyed by session, not by session state: a continued conversation updates its
// summary rather than orphaning it.
func File(s *session.Session) string {
	return filepath.Join(Dir(), s.Agent.String()+"-"+s.ID+".json")
}

func Load(s *session.Session) (Record, bool) {
	b, err := os.ReadFile(File(s))
	if err != nil {
		return Record{}, false
	}
	var rec Record
	if json.Unmarshal(b, &rec) != nil || rec.Text == "" {
		return Record{}, false
	}
	return rec, true
}

func save(s *session.Session, rec Record) {
	if err := os.MkdirAll(Dir(), 0o755); err != nil {
		return
	}
	if b, err := json.MarshalIndent(rec, "", "  "); err == nil {
		os.WriteFile(File(s), b, 0o644)
	}
}

// Generate produces or updates a session's summary. It is slow — several
// seconds — so callers should treat it as a background job.
func Generate(s *session.Session, cfg config.Summary) (Record, error) {
	argv := cfg.For(s.Agent.String())
	if len(argv) == 0 {
		return Record{}, errNoCommand
	}

	prompt, gen, err := buildPrompt(s, cfg.InputBudget(s.Agent.String()))
	if err != nil {
		return Record{}, err
	}

	ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
	defer cancel()

	cmd := exec.CommandContext(ctx, argv[0], argv[1:]...)
	cmd.Stdin = strings.NewReader(prompt)
	cmd.Dir = s.Cwd // some CLIs refuse to start outside a workspace
	out, err := cmd.Output()
	if err != nil {
		return Record{}, err
	}

	text := strings.TrimSpace(string(out))
	if cfg.MaxChars > 0 {
		text = format.Truncate(text, cfg.MaxChars)
	}
	if text == "" {
		return Record{}, errEmptySummary
	}

	rec := Record{
		Text:         text,
		CoveredUntil: s.Modified,
		CoveredMsgs:  s.Msgs,
		Generation:   gen,
		Written:      time.Now(),
	}
	save(s, rec)
	return rec, nil
}

// buildPrompt chooses between a full summarisation and an incremental update,
// and returns the generation number the result will carry.
func buildPrompt(s *session.Session, budget int) (string, int, error) {
	if prev, ok := Load(s); ok && prev.Stale(s) && prev.Generation < MaxIncrements {
		since, err := transcriptSince(s, prev.CoveredUntil, budget)
		// If the "new" part is most of the conversation, updating from the old
		// summary buys nothing over reading the transcript properly.
		if err == nil && since != "" && prev.Behind(s)*3 < s.Msgs {
			return strings.Replace(updatePrompt, "{{PREV}}", prev.Text, 1) + since,
				prev.Generation + 1, nil
		}
	}
	excerpt, err := transcriptExcerpt(s, budget)
	if err != nil {
		return "", 0, err
	}
	return fullPrompt + excerpt, 0, nil
}

type summaryError string

func (e summaryError) Error() string { return string(e) }

const (
	errNoCommand    = summaryError("no summary command configured for this provider")
	errEmptySummary = summaryError("summariser returned nothing")
)

// transcriptSince returns only the messages recorded after a given time. This
// is what keeps an active session cheap to stay on top of: the input is
// proportional to what changed, not to how long the conversation has run.
func transcriptSince(s *session.Session, since time.Time, maxChars int) (string, error) {
	if s.Path == "" {
		return "Latest prompt: " + s.Last, nil // copilot has no transcript file
	}
	f, err := os.Open(s.Path)
	if err != nil {
		return "", err
	}
	defer f.Close()

	var parts []string
	total := 0
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 256*1024), 64*1024*1024)
	for sc.Scan() {
		line := sc.Bytes()
		if ts := RecordTime(line); ts.IsZero() || !ts.After(since) {
			continue
		}
		text := strings.TrimSpace(format.Clean(session.RecordText(line)))
		if text == "" {
			continue
		}
		text = format.Truncate(text, 600)
		parts = append(parts, text)
		total += len(text)
		for total > maxChars && len(parts) > 1 {
			total -= len(parts[0]) // overflow drops the oldest; recency wins
			parts = parts[1:]
		}
	}
	return strings.Join(parts, "\n"), nil
}

func RecordTime(line []byte) time.Time {
	var r struct {
		Timestamp string `json:"timestamp"`
	}
	if json.Unmarshal(line, &r) != nil || r.Timestamp == "" {
		return time.Time{}
	}
	return session.EventTime(r.Timestamp, time.Time{})
}

// transcriptExcerpt builds the input for a full summarisation: the opening of
// the conversation plus its tail. The middle is where tool output lives, which
// is bulky and tells you least about intent.
func transcriptExcerpt(s *session.Session, maxChars int) (string, error) {
	const (
		headLines = 12
		tailLines = 40
	)
	if maxChars <= 0 {
		maxChars = 12000
	}
	if s.Path == "" {
		return "Title: " + s.Title + "\nLast prompt: " + s.Last, nil
	}

	f, err := os.Open(s.Path)
	if err != nil {
		return "", err
	}
	defer f.Close()

	var head, tail []string
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 256*1024), 64*1024*1024)
	for sc.Scan() {
		text := strings.TrimSpace(format.Clean(session.RecordText(sc.Bytes())))
		if text == "" {
			continue
		}
		text = format.Truncate(text, 600)
		if len(head) < headLines {
			head = append(head, text)
			continue
		}
		tail = append(tail, text)
		if len(tail) > tailLines {
			tail = tail[1:]
		}
	}

	parts := head
	if len(tail) > 0 {
		parts = append(parts, "[...]")
		parts = append(parts, tail...)
	}
	out := strings.Join(parts, "\n")
	if len(out) > maxChars {
		// Keep both ends: the opening says what the session was for, the tail
		// says how it went. Cutting only the front would lose the intent.
		// Cut on rune boundaries — a half-character at either seam is a byte of
		// noise in the model's input.
		half := maxChars / 2
		out = format.SliceRunes(out, 0, half) + "\n[...]\n" + format.SliceRunes(out, len(out)-half, len(out))
	}
	if strings.TrimSpace(out) == "" {
		return "", errEmptySummary
	}
	return out, nil
}

// Prune drops cache entries for sessions that no longer exist. Entries
// for sessions that merely moved on are kept — they are the basis of the next
// incremental update.
func Prune(sessions []*session.Session) {
	live := map[string]bool{}
	for _, s := range sessions {
		live[filepath.Base(File(s))] = true
	}
	entries, err := os.ReadDir(Dir())
	if err != nil {
		return
	}
	for _, e := range entries {
		if !live[e.Name()] {
			os.Remove(filepath.Join(Dir(), e.Name()))
		}
	}
}
